on:
  schedule:
    - cron:  "0 5 * * *"
  workflow_dispatch:

name: Script_R_ONDE_carto_auto

jobs:
  run-r-script:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deploy
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: 4.2.2
      
      - name: installation sf
        run: |
          Rscript -e 'install.packages("sf")'

      - uses: r-lib/actions/setup-r-dependencies@v2
            
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1' # Pandoc version pour compiler.
        
      - name: Verifier maj
        run: |
          Rscript "01_verifier_maj.R"
          
      - name: Telechargement donnees
        run: |
          Rscript "02_telechargement_data.R"
          
      - name: Preparation donnees
        run: |
          Rscript "03_preparer_data.R"
      
      - name: Preparation graphiques
        run: |
          Rscript "04_preparer_graphiques.R"
          
      - name: Commit Results 
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script $(date)" || echo "No changes to commit"
          git push origin -f || echo "No changes to commit"-

      - name: Render rapport
        run: |
          Rscript "05_generer_rapport_html.R"
          
      - name: Commit Page 
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.html
          git commit -m "Render Rmarkdown $(date)" || echo "No changes to commit"
          git push origin || echo "No changes to commit"-    
