name: Synchronisation branche deploy

on:
  push:
    branches: [master]
      
jobs:
  merge_to_deploy:
    name: merge master in deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          
      - name: Merge master back to deploy
        run: |
          git fetch --unshallow
          git checkout deploy
          git pull
          git merge --no-ff master -m "Auto-merge master back to deploy"
          git push
          
  run-r-script:
    name: update data
    needs: merge_to_deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: deploy
          
      - name: Run R scripts in Docker
        run: |
          docker run --volume ${{ github.workspace }}:/workspace --workdir /workspace ofbidf/r_prr_onde:latest bash -c "
          Rscript '01_forcer_maj.R'
          Rscript '02_telechargement_data.R'
          Rscript '03_preparer_data.R'
          Rscript '04_preparer_graphiques.R'
          Rscript '05_generer_rapport_html.R'
          "
          
      - name: Commit Results 
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results $(date)" || echo "No changes to commit"
          git push origin -f || echo "No changes to commit"  
